#!/bin/bash


#
# Setup rsyslog logging
#

cat << EOF | sudo tee /etc/rsyslog.d/$1.conf
if \$programname == '$1' then
/var/log/$1.log
& stop
EOF

sudo systemctl restart rsyslog.service

#
# Setup systemd service for automatic restart on power failure
#

cat << EOF | sudo tee /lib/systemd/system/$1.service
[Unit]
Description=$1
ConditionPathExists=/home/$USER/go/bin/$1
After=network.target

[Service]
Type=simple
User=$USER

WorkingDirectory=/home/$USER/projects/$1
ExecStart=/home/$USER/go/bin/$1

Restart=on-failure
RestartSec=1

StandardOutput=syslog
StandardError=syslog
SyslogIdentifier=$1

[Install]
WantedBy=multi-user.target
EOF

sudo systemctl daemon-reload
sudo systemctl enable $1
sudo systemctl restart $1
sudo systemctl status $1
