#!/bin/bash

echo "Checking setup..."

go version >/dev/null 2>&1
if [ $? -ne 0 ]; then
   echo "Go missing.  Install Go with:"
   echo ""
   echo "    sudo apt update"
   echo "    sudo apt install golang -y"
   echo ""
   exit 1
fi

gcc --version >/dev/null 2>&1
if [ $? -ne 0 ]; then
   echo "gcc missing.  Install gcc with:"
   echo ""
   echo "    sudo apt update"
   echo "    sudo apt install gcc -y"
   echo ""
   exit 1
fi

sudo apt-get -y install libpam0g-dev >/dev/null 2>&1

tags=""
if [ ! -z "$1" ]; then
    tags="$1"
fi

tmpFile="/tmp/$USER-merle-build"
go list -tags "$tags" -f '{{.Dir}} {{.Target}}' ./... >$tmpFile

while read -r line; do
	args=($line)
	if [ ! -z ${args[1]} ]; then
		echo "Building ${args[1]}..."
		cd ${args[0]}
		go build -tags "$tags" ./...
		if [ $? -ne 0 ]; then
			break
		fi
		go clean -tags "$tags" ./...
		go install  -tags "$tags" ./...
		sudo setcap CAP_NET_BIND_SERVICE=+eip ${args[1]}
	fi
done <$tmpFile

rm $tmpFile
